spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: *****
    password: ********
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
springdoc:
  default-produces-media-type: application/json




 
